version: "3"

services:
  rocketArena3:
    image: alcachofass/ra3server
    restart: always
    ports:
      - "27961:27961/udp"
    volumes:
      - "${PWD}/arena:/usr/lib/ioquake3/arena"
      - "${PWD}/baseq3:/usr/lib/ioquake3/baseq3"
